### ISSUE TITLE
Support dot in localized keys

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Lang.js#54]
This issue was originally reported at: https://github.com/rmariuzzo/Laravel-JS-Localization/issues/115 by @ERPedersen.

The following [test](https://github.com/rmariuzzo/Lang.js/blob/e2850ca5f3bcdf97a2cd90c8a8f64ea28c709466/test/spec/lang_get_spec.js#L68-L70) will not work:

```js
it('should return the expected message if the key has a dot', function() {
  expect(lang.get('messages.dot.in.key')).toBe('Dot In Key');
})
```

By default, Lang.js interpret `.` as separators. Therefore, we would to detect if a key exist with the dot.

### Steps to reproduce

 1. `git clone https://github.com/rmariuzzo/Lang.js`
 2. `git checkout develop`
 3. `npm run test`

### Tasks 

 - [x] Support simple dot key.
 - [x] Support nested dot key.
 - [x] Support tricky dot key.
